version: '3'

services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"

  client-gateway:
    build: ./client-gateway-prueba-tecnica
    ports:
      - "${PORT_GATEWAY}:3000"
    volumes:
      - ./client-gateway-prueba-tecnica/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PORT_GATEWAY}
      - NATS_URL=nats://nats-server:4222

  auth-server:
    depends_on:
      - db-auth
    build: ./auth-ms-prueba-tecnica
    volumes:
      - ./auth-ms-prueba-tecnica/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PORT_AUTH_MS}
      - NATS_URL=nats://nats-server:4222
      - DB_PASSWORD=${DB_PASSWORD_AUTH}
      - DB_NAME=${DB_NAME_AUTH}
      - DB_HOST=${DB_HOST_AUTH}
      - DB_PORT=${DB_PORT_AUTH}
      - DB_USERNAME=${DB_USERNAME_AUTH}
      - SECRET_JWT=${SECRET_JWT}

  db-auth:
    image: postgres:16.2
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME_AUTH}
      POSTGRES_PASSWORD: ${DB_PASSWORD_AUTH}
      POSTGRES_DB: ${DB_NAME_AUTH}
    container_name: db-auth
    volumes:
      - ./auth-ms-prueba-tecnica/postgres:/var/lib/postgresql/data

  product-server:
    depends_on:
      - db-product
    build: ./products-ms-prueba-tecnica
    volumes:
      - ./products-ms-prueba-tecnica/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PORT_PRODUCT_MS}
      - NATS_URL=nats://nats-server:4222
      - DB_PASSWORD=${DB_PASSWORD_PRODUCT}
      - DB_NAME=${DB_NAME_PRODUCT}
      - DB_HOST=${DB_HOST_PRODUCT}
      - DB_PORT=${DB_PORT_PRODUCT}
      - DB_USERNAME=${DB_USERNAME_PRODUCT}

  db-product:
    image: postgres:16.2
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME_PRODUCT}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PRODUCT}
      POSTGRES_DB: ${DB_NAME_PRODUCT}
    container_name: db-product
    volumes:
      - ./products-ms-prueba-tecnica/postgres:/var/lib/postgresql/data
 
  